# Changes here will be overwritten by Copier
_commit: c2d7118
_src_path: https://github.com/browniebroke/pypackage-template
cli_name: aiovlc
copyright_year: '2025'
documentation: true
email: marhje52@gmail.com
full_name: Martin Hjelmare
github_username: MartinHjelmare
has_cli: true
initial_commit: false
is_django_package: false
open_source_license: Apache Software License 2.0
package_name: aiovlc
project_name: aiovlc
project_short_description: Control VLC over telnet connection using asyncio
project_slug: aiovlc
run_uv_sync: false
setup_github: false
setup_pre_commit: true

