tasks:
  - command: |
      pip install poetry
      PIP_USER=false poetry install --extras cli
  - command: |
      pip install pre-commit
      pre-commit install
      PIP_USER=false pre-commit install-hooks
