name: Upgrader

on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 6 * *"

jobs:
  upgrade:
    uses: browniebroke/github-actions/.github/workflows/uv-upgrade.yml@v1
    secrets:
      gh_pat: ${{ secrets.GITHUB_TOKEN }}
